### ISSUE TITLE
Update commits from 17.0.3

### ISSUE THREAD

**Issue by AndrewLeedham** [semantic-release-plus/semantic-release#60]
17.03 was just release with a fix for SSH auth. Can said changes be cherry-picked into this fork. I would put a PR in for this, but it does not seem like that is your usual process. Thanks 😃 

See https://github.com/semantic-release/semantic-release/issues/1454

**Comment by AndrewLeedham** [comment]
@JoA-MoS anything I can do to help push this along?

**Comment by JoA-MoS** [comment]
Sorry Andrew, I missed your comment. I  synced upstream to this fork, so you should be good. I'm open to better process recommendations if you have them. So far there hasn't been a need to cherry pick anything.

**Comment by JoA-MoS** [comment]
This should be addressed in 18.0.1

**Comment by AndrewLeedham** [comment]
Process seems fine, just wasn't sure if there was a way I could put a PR in to sync with upstream.

Thanks for updating :)
